databases:
  - name: love-story-db
    plan: free

services:
  - type: web
    name: love-story
    env: python
    plan: free
    buildCommand: |
      python manage.py collectstatic --noinput
    startCommand: python manage.py runserver 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "0"
      - key: DJANGO_ALLOWED_HOSTS
        value: love-story-4o6w.onrender.com
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: https://love-story-4o6w.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: love-story-db
          property: connectionString
